### ISSUE TITLE
getInstallsSteamWindows fails with library on other drive

### ISSUE THREAD

**Issue by s-monette** [mircearoata/SatisfactoryModLauncherAPI#4]
Hi, I had an issue with:
SatisfactoryModManager: v2.0.1

It was unable to find the Satisfactory Steam install path.

On my setup Steam is installed in:
**C:\Program Files (x86)\Steam**

And I have another library in:
**F:\SteamLibrary**

It seams the function **getInstallsSteamWindows** in **SatisfactoryModManagerAPI** looks into the file:
**C:\Program Files (x86)\Steam\steamapps\libraryfolders.vdf** for the library path, which pointed to **F:\\SteamLibrary**, which is good.

But then the function try to find the game .acf at the root of this folder and fails.
I manually edited the path in **libraryfolders.vdf** to **F:\SteamLibrary\steamapps** instead, and then SMM was able to detect the game .acf.
The changes made to **libraryfolders.vdf** will be overwritten by Steam upon relaunching.
So a proper fix should be made in the lib instead.

Let me know if you need help to test potential solutions!

**Comment by mircearoata** [comment]
This, as you described it, is just plain not possible, as [this line](https://github.com/mircearoata/SatisfactoryModManagerAPI/blob/50d7618d7b89441bab17292e9242297e84d4d58f/src/installFinder.ts#L151) specifically appends \steamapps

Do you have any error logs?

**Comment by s-monette** [comment]
I tried to enable the debug mode option in SMM, but no additional log files seems to be created.
Is there a better way to create/extract the error log ?

**Comment by s-monette** [comment]
I installed nodejs and ran SMM in console, now I can see the debug log.
The main error is:
[ERROR]	File not found -
F:/SteamLibrary/steamapps/common/Satisfactory/FactoryGame/Binaries/Win64/FactoryGame-Win64-Shipping.exe

Which is in fact in:
C:\Program Files (x86)\Steam\steamapps\common\Satisfactory\FactoryGame\Binaries\Win64\FactoryGame-Win64-Shipping.exe

I'll try to check if there is a better way to find in which library a game is installed.

**Comment by mircearoata** [comment]
`%localappdata%\SatisfactoryModManager\logs` is where the logs are

And there is no better way, Steam doesnt like to share anything, you can see what had to be done (find Steam in registry, get libraries list, check each library, get the game version from exif) while Epic has all that info easy to get in the same place on every PC...

**Comment by s-monette** [comment]
kind of figured out what the problem was, I had appmanifest_526870.acf in both libraries folders.
I suppose it was a leftover from when I moved the game from the HDD(f:) to the NVME(c:).

Yeah as you said the current code do what is expected and Steam does not seams to really provide a straight forward way to finding a game folder.

The only improvement I could see would be to do the **fs.existsSync** on the **FactoryGame-Win64-Shipping.exe** path for each elements in **libraryfolders** instead of relying on **appmanifest_526870.acf** presence.

But I maybe the only one with a fringe case of botched game folder migration.
The choice is yours how you want to handle that case ;)

Thanks for the support and the time you invested in this project, take care!

**Comment by mircearoata** [comment]
I hoped that Steam wouldn't end up with leftover files when moving the game like Epic does, but it turns out it does. I'll add a check for the exe existing and if not, add the path to the list of broken installs to show the user

**Comment by mircearoata** [comment]
This was fixed in API v2.0.2
